project:
  type: website

website:
  title: "Finanças com R"
  navbar:
    left:
      - href: Pratica.qmd
        text: Inicio
      - Apresentacao.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

